### ISSUE TITLE
Epoch subseconds should retain number of digits after the decimal point

### ISSUE THREAD

**Issue by tmr08c** [taxjar/date_time_parser#15]
When working on #10, I believe I ran into some unexpected behavior with epoch subseconds. 

# Current Behavior

Currently, the epoch's subsecond does not track the number of leading `0`s. This works for tests like:

```elixir
test_datetime_parsing(
  "9999999999.999999",
   DateTime.from_naive!(~N[2286-11-20T17:46:39.999999], "Etc/UTC")
)

test_datetime_parsing(
  "9999999999.9999999999",
  DateTime.from_naive!(~N[2286-11-20T17:46:39.999999], "Etc/UTC")
)
```

because they do not have leading `0`s.

However, for a test with leading `0`s after the `.` we get unexpected behavior:

```elixir
test_datetime_parsing(
   "0000000000.0000000001",
   DateTime.from_naive!(~N[1970-01-01T00:00:00.000001], "Etc/UTC")
)


  1) test parse_datetime/1 - epoch parses datetime 0000000000.000001 (DateTimeParserTest)
     test/date_time_parser_test.exs:168
     Assertion with == failed
     code:  assert datetime == expected
     left:  ~U[1970-01-01 00:00:00.1Z]
     right: ~U[1970-01-01 00:00:00.000001Z]
     stacktrace:
       test/date_time_parser_test.exs:168: (test)
```

Rather than the subsecond time be `000001` we get `1`. 

## Why I think this is happening

I believe this is happening because [`NimbleParsec.integer/2`](https://hexdocs.pm/nimble_parsec/NimbleParsec.html#integer/2) (which is [how subseconds are parsed](https://github.com/tmr08c/date_time_parser/blob/05da5cdae76c24867e5190a9098d2e82ef91d808/lib/combinators/epoch.ex#L20-L24)) is parsing **integers** and in integers leading `0`s are unimportant. 

When running the sample test above (where the input is `"0000000000.0000000001"`) I receiving the following tokens:

```elixir
Tokens: [unix_epoch: 0, unix_epoch_subsecond: 1]
```

# Expected Behavior

I _think_ we should expect the leading `0`s to be preserved.

## What Ruby does

I know you check against what Ruby does, and here are some Ruby examples:

```ruby
# ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
# Rails 6.0.0
Time.at(1.0000000001).utc.iso8601(10)
=> "1970-01-01T00:00:01.0000000001Z"

Time.at(1.0000100001).utc.iso8601(10)
=> "1970-01-01T00:00:01.0000100001Z"
```

### 6 digits

It looks like currently subsecond support only does up to 6 digits. For a case like `1.00000001` I _think_ this would mean dropping the `1`, but I'm not sure if it would ever make sense to round (e.g., `1.0000009` to `00:00:01.000001`). 

### Ruby things

Ruby does things that are unexpected to me, but I'm not sure if they are done for a reason. 

Some examples:

```ruby
# why does it use multiple 9s instead of the 1?
Time.at(1.000001).utc.iso8601(10)
=> "1970-01-01T00:00:01.0000009999Z"

# with is it using 3 instead of 4 
Time.at(1.000004).utc.iso8601(6)
=> "1970-01-01T00:00:01.000003Z"
# using more digits seems to show more 9s after the 3
Time.at(1.000004).utc.iso8601(10)
=> "1970-01-01T00:00:01.0000039999Z"
``` 

# Fixing

Some potential ideas of how to solve this:

* Parse the subsecond as a string in `DateTimeParser.Combinators.Epoch.unix_epoch_subsecond/0` and handle converting it to a float in `DateTimeParser.Epoch`.  I _think_ converting could work like:

```elixir
> subsecond = "000001"
"000001"
> {f, _} = Float.parse("0." <> subsecond)
{1.0e-6, ""}
> 1.0 - f
0.999999
```

* Moving to Regular Expressions. This came up when @dbernheisel was helping me work on #10. I _think_ this would result in something similar to the above solution, but more changes, so it may be preferrable to avoid.

**Comment by tmr08c** [comment]
@dbernheisel I would like to try to help with this, but I wanted to get your thoughts and check my process before moving forward. 

This is blocking #10 because when working with negatives you need to do something like `1.0 - subseconds` to handle moving backward, and receiving subseconds as an integer is causing issues with that.

**Comment by dbernheisel** [comment]
great catch. thanks. I remember having this problem in the tokenizer as well and fixing it there.

I think using nimbleparsec for this might be overkill and isn't making it easier. It's great for the other tokenizer, but when we know it's an epoch time which has a simple representation, _and_ we already have a regex to capture it, we can consolidate.

I think moving to a regex-based parser for Epochs will help make this easier to fix.

right now for epochs we have `\A\d{10,11}(?:\.\d{1,10})?\z`. If we adjust it to this: `\A(?<second>-?\d{10,11})(?:\.(?<subsecond>\d{1,10}))?\z` then that will give named groups as strings and we can use that for tokens via `Regex.named_captures`. I'll be happy to pair on it if we can sync up. Otherwise this may be a lead to start on it.

**Comment by tmr08c** [comment]
Thanks for the follow-up, @dbernheisel. I am a little strapped for time this week but would like to help out next week if this can wait.

**Comment by tmr08c** [comment]
@dbernheisel I started poking around on this and wanted to get your thoughts on  some things.
 I figured I'd write this up to have some breadcrumbs for future me, and see if you notice any red flags.

### Tokens

Currently, it looks like `Serial.parse/1` returns its tokens as a keyword list:

https://github.com/taxjar/date_time_parser/blob/0f1e9eaa4d9f62bf91847f154a46f634b0d11639/lib/serial.ex#L4-L14

Is this to match how `NimbleParsec` does things? When pairing on #14, we talked about how keyword lists can make pattern matching tricky. If we move towards [using named captures](https://github.com/taxjar/date_time_parser/issues/15#issuecomment-541654619) it may be nice to leverage the map of named matches that are returned. 

I haven't dug extensively, but it looks like `tokens` are generally passed in all together and there isn't an expectation of type in the general code (only in the individual parsers/combinators), so I'm thinking it may be possible to use a map if we want. Any concerns with trying out a map and breaking the expected return we would get from `NimbleParsec`?

### Epoch calculation logic

Currently, the seconds are parsed using `DateTime.from_unix` and then, if they exist the sub-seconds/microseconds are parsed and added to the struct: 

https://github.com/taxjar/date_time_parser/blob/0f1e9eaa4d9f62bf91847f154a46f634b0d11639/lib/epoch.ex#L10-L24

When looking at the docs for [`DateTime.from_unix/3`](https://hexdocs.pm/elixir/DateTime.html#from_unix/3) I saw that you can pass the `unit`. This got me thinking that we could convert the parsed time into microseconds and pass that into `DateTime.from_unix`:

```elixir
# 999999999.999999
DateTime.from_unix(9999999999 * 1000000 + 999999, :microsecond)   
{:ok, ~U[2286-11-20 17:46:39.999999Z]}
````

I'm not 100% sure how the parsing will turn out yet, but potentially this could allow for `Epoch.from_token/1` to leverage pattern matching:

```elixir
from_token(%{seconds: seconds, subseconds: subseconds}) do
  DateTime.from_unix(seconds * 1000000 + subseconds, :microseconds)
end

from_token(%{seconds: seconds}) do
  DateTime.from_unix(seconds * 1000000 + subseconds)
end
```

I'm not sure if this will become overly complicated when adding in negative epoch support (#10):

```elixir
from_token(%{sign: "-", seconds: seconds, subseconds: subseconds}) do
  DateTime.from_unix(-1 * seconds * 1000000 - subseconds, :microseconds)
end
```

Very small test caes, but in practice looks like it lines up with the ruby example: 

```elixir
Example
DateTime.from_unix(-1 * 1000000 - 1, :microsecond)
{:ok, ~U[1969-12-31 23:59:58.999999Z]}
```

**Comment by dbernheisel** [comment]
moving the tokens into a map will require a small refactor on the other parsers. That's fine, but for this let's stick with the keyword list (and if you think the map is worth it, let's have that in another PR). The serial parser returns a keyword list because that's how NimbleParsec returns the tokens from parsing the string, and I copied that return structure for consistency.

I think going with the regex named captures and returning it as a Keyword list is the simplest way forward for now. Something like this? 

```elixir
def parse(string) do
  # i'd prefer to use the same module attribute so it's not duplicated though..
  found_tokens = Regex.named_captures(~r|\A(?<second>-?\d{10,11})(?:\.(?<subsecond>\d{1,10}))?\z|, string) || %{}

  found_tokens
  |> Enum.map(fn k, v ->
    {integer, ""} = Integer.parse(v)
    {k, integer}
  end)
  |> Enum.into([])
end
```

Great catch on DateTime.from_unix re: microseconds. I totally missed that. That will be much better for us to use instead of stitching it back together in the struct ourselves.

**Comment by tmr08c** [comment]
> Great catch on DateTime.from_unix re: microseconds. I totally missed that. That will be much better for us to use instead of stitching it back together in the struct ourselves.

It looks like using a unit of microseconds will cause us to always have subseconds/microseconds show up in the timesample:

```elixir
 DateTime.from_unix(000000000, :microsecond)
{:ok, ~U[1970-01-01 00:00:00.000000Z]}
```

Currently, the tests do not expect this behavior:

```elixir
test parse_datetime/1 - epoch parses datetime 99999999999 (DateTimeParserTest)
     test/date_time_parser_test.exs:143
     Assertion with == failed
     code:  assert datetime == expected
     left:  ~U[5138-11-16 09:46:39.000000Z]
     right: ~U[5138-11-16 09:46:39Z]
     stacktrace:
       test/date_time_parser_test.exs:143: (test)
```

Based on the example you shared in #10, I'm not sure if this is how Ruby would handle things or a result of passing in `10` to `iso8601`:

```ruby
Time.at(-1).utc.iso8601(10)
=> "1969-12-31T23:59:59.0000000000Z"
```

If always including the microseconds is okay, I think the code may be easier to work with. I made a draft PR (#16) so you can take a look at the code and see if it's worth the tradeoff.

**Comment by tmr08c** [comment]
We talked about this during project night and do not want to go with the approach in #14. We want to make sure we keep the same number of significant digits that were passed in.
