### ISSUE TITLE
Add option to turn off parsers

### ISSUE THREAD

**Issue by dbernheisel** [taxjar/date_time_parser#19]
There's a scenario where a user may not want to enable "epoch" or "serial" time parsing. That way, strings like "31" aren't accepted.

Perhaps an interface could look like:
```elixir
parsers = [DateTimeParser.Serial, DateTimeParser.Epoch, DateTimeParser.Default]
DateTimeParser.parse("42", parsers: [DateTimeParser.Default])
# => {:error, "Could not parse 42"}
```

**Comment by cas27** [comment]
What do you think about having the default list of parsers set at the config level, and then you could override when you make a parse call like you have exampled above?

**Comment by dbernheisel** [comment]
Yea that sounds great.

```elixir
# in config
config DateTimeParser, parsers: [
  DateTimeParser.Serial,
  DateTimeParser.Epoch,
  DateTimeParser.Default
]

# in app code
DateTimeParser.parse(my_string) #=> uses the allowed parsers above in config 
DateTimeParser.parse(my_string, parsers: [DateTimeParser.Default]) #=> uses the passed-in parsers.
```

Perhaps that could even determine the order of which to try parsers.
