### ISSUE TITLE
Support for languages other than US English

### ISSUE THREAD

**Issue by x-ji** [taxjar/date_time_parser#38]
Hi, we're looking for a library to parse dates. `date_time_parser` is working pretty well for American dates, but we also have data from European languages (e.g. German, French). An example would be `04 août 2020`.

[A similar library in Python](https://dateparser.readthedocs.io/en/latest/) is able to support languages other than US English, however this library doesn't seem to have such capabilities. Is this something you might consider adding? Or maybe this topic could be open for a potential PR (we might not have time to submit it soon though)? Thanks.

**Comment by dbernheisel** [comment]
yes of course! I personally don't have an immediate need for non-English languages at the moment, but as soon as I do I'll be happy to add it myself; in the meantime, PRs are always welcome.
