### ISSUE TITLE
Support for month-year formats

### ISSUE THREAD

**Issue by maciejgryka** [taxjar/date_time_parser#48]
This might be out of scope, but it would be nice to predictably parse strings like `Jan 2020`, `October 1995`, `May 1442` etc. What happens today is that all of these get interpreted as e.g. `October 19 95`, so basically `%b %d%y` instead of `%b %Y`.

```elixir
iex(1)> DateTimeParser.parse("Jan 2020")
{:ok, ~D[2020-01-20]}
iex(2)> DateTimeParser.parse("October 1995")
{:ok, ~D[1995-10-19]}
iex(3)> DateTimeParser.parse("May 1442")
{:ok, ~D[2042-05-14]}
```

I'd expect `DateTimeParser.parse("Jan 2020")` to produce `~D[2020-01-01]}`, i.e. always default to the first day of the month.

**Comment by dbernheisel** [comment]
You might try the `assume_date` option and see if that helps, for example:

```elixir
iex> DateTimeParser.parse("Jan 2020", assume_date: ~D[0001-12-01])
{:ok, ~D[2020-01-20]}
```

Having a default to the first day of the month goes against a principle since we released 1.x, which is **no data** is better than **assumed data**.

However in your 2nd and 3rd example, those guesses are pretty bad, so I'll see if there's an optimization we can make here.

**Comment by dbernheisel** [comment]
I have a spike on this branch if you want to try it out:
https://github.com/taxjar/date_time_parser/tree/db-month-year-format

Keep in mind this is a branch of a branch, so it might take a bit for me to get it merged into the main branch.

**Comment by maciejgryka** [comment]
Cool, thanks @dbernheisel that makes a lot of sense. I totally support "no data is better than assumed data " and it's great to have `assume_date` as an option. I tried out that branch and it seems to be working as expected.

Also, just curious, does the `12` in `~D[0001-12-01]` basically mean "if no month is specified, assume December"?

**Comment by dbern-stripe** [comment]
@maciejgryka that's right.
